use_frameworks!

target 'ZZNetworking_Example' do
  pod 'ZZNetworking', :path => '../'

  target 'ZZNetworking_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
